### ISSUE TITLE
[RFE] retrieve the correct path for authorized key file from sshd config

### ISSUE THREAD

**Issue by anhvoms** [Azure/azure-init#97]
## Current situation
azure-init assumes that the authorized key file is $HOME/.ssh/authorized_keys which might not be what the sshd is configured to look for (/etc/sshd/config/AuthorizedKeysFile)

## Impact

azure-init might write the provided public key to a place that is not expected by sshd, which will render the VM inaccessible via the provided key

## Ideal future situation

azure-init should process the sshd config to correctly determine where to write the authorized key file.

## **Implementation options

We likely need a module to handle various ssh related functionality. #67 will also benefit from such module

**Comment by jeremycline** [comment]
I spent a few minutes looking into this, so I'm leaving my findings here in case someone else wants to work on it before I get around to it:

`sshd` has a `-G` parameter to print out the effective configuration (not sure what version added this, hopefully it's very old). This is useful since many distributions have a directory with config snippets, settings might be specified more than once and we'd need to match sshd's parsing rules, and there's tokens which can be expanded (`%h` for example, to specify the user's home directory). So, what we probably want to do is:

1. Run `sshd -G` and collect the stdout from the command. It seems to print out setting keys all lower case - setting keys are case-insensitive so that's nice.
2. Each setting is a line, so search for the line that starts with `authorizedkeysfile`. There should be only one match.
3. Multiple keyfile locations can be specified, but we're writing keys and not reading them so we can just take the first item
4. If the item is an absolute path that's where to write the keys. If it's relative, it's relative to the user's home directory. It could be set to none.

If the setting is `none` we could either change the setting to `.ssh/authorized_keys` or fail provisioning. Changing the configuration is definitely the harder of the two options because of the config snippets and so on. It would probably look like:

1. Remove any instance of `authorizedkeysfile` (case insensitive) from `/etc/ssh/sshd_config`.
2. Manually parse `/etc/ssh/sshd_config` for `include` settings (these can include glob wildcards and be relative to /etc/ssh or be absolute paths)
3. Either chase each include to ensure it doesn't contain `authorizedkeysfile` OR insert `authorizedkeysfile .ssh/authorized_keys` before the first `include` directive to ensure our setting is picked up.
4. Verify by rerunning `sshd -G`.

IMO if the image doesn't include the correct config we should just fail (with a helpful message) rather than try to patch it up ourselves.

**Comment by balakreddy** [comment]
Assigning this issue to myself. I will be working on this issue.
Thanks
